const FETCH_USER_LOADING = "FETCH_USER_LOADING";
const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
const FETCH_USER_FAILURE = "FETCH_USER_LOADING";

export { FETCH_USER_LOADING, FETCH_USER_SUCCESS, FETCH_USER_FAILURE };
